Do not print anything when pipe is broken
BrokenPipeError: [Errno 32] Broken pipe

This should NOT be done if acting on these interrupts is required (say,
for clean up).

http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python
http://newbebweb.blogspot.co.uk/2012/02/python-head-ioerror-errno-32-broken.html